S = "spams"
print(S)
S = "spams"
print(S)
print("привет")
print("1: \t", ord("s"))
print("\t2: ", chr(100))
str = "string"
print("3: \t", str)
print("4: \t", str[0])
print("5: \t", str[2])
print("6: \t", str[-1])
print("7: \t", str[0:3])
print("8: \t", str[:3])
print("9: \t", str[::-1])
print("10: \t", str[0:5:2])
print("11:", str[:])
print("12:", str[0:0])
print("first\nsecond")
print("m" in "eam")
print("I" not in "team")
print(len("abracadabra"))
s = "abracadabra"
print(s.find("ab"))
print(s.rfind("ab"))
print(s.find("x"))
print("abracadabra".count("a"))
print("abracadabra".startswith("abra"))
print(str.endswith("g"))
print("-".join(["Миру", "мир"]))
print("Раз два три!".split("а"))
print("Раз два три".split())
print("Раз два три!".replace("а", "я"))
print("100".isdigit())
print("abc".isalpha())
print("E315".isalnum())

